### ISSUE TITLE
C bindings (feature request)

### ISSUE THREAD

**Issue by ringerc** [jaegertracing/cpp-client#37]
The Jeager client doesn't appear to have any C bindings, making it unusable from pure C programs without a lot of abstraction boilerplate.

It shouldn't be necessary to have separate C bindings, but an API to expose the C++ bindings via `extern "C"` functions and an opaque context struct would be a huge help.

I was eager to plug this into PostgreSQL and extend our existing dtrace/perf_sdt tracepoints with some context info so we could use them to create spans. But it's going to be pretty hard to do with a pure C++ codebase.

If I get the chance to write some minimal bindings I'll update here.

**Comment by yurishkuro** [comment]
cf https://github.com/opentracing/opentracing-cpp/issues/26

I think C binding doesn't have to be Jaeger-specific, it could be shared by all OpenTracing tracers.

**Comment by isaachier** [comment]
Yes @yurishkuro is correct here. When I spoke about focusing on specific tracing implementations [here](https://github.com/opentracing/opentracing-cpp/pull/27#issuecomment-360117902), I really meant to say that the **config file** should detail the overrides for a given tracer. So if you want to use a probabilistic sampler with 5% sampling in Jaeger, that would be specified in your config file. However, I would avoid using any code from this repo directly (except maybe the global tracer initialization, depending on the outcome of https://github.com/opentracing/opentracing-cpp/pull/45).

**Comment by ringerc** [comment]
OK, makes sense. Closing accordingly, others can find it when they look.
