### ISSUE TITLE
Extract() failure returns opentracing::expected with has_value=t and null ptr

### ISSUE THREAD

**Issue by ringerc** [jaegertracing/cpp-client#55]
Calling `jaegertracing::Tracer`'s `Extract(std::istream& reader) )` with an empty stream produces what I'd consider an unexpected result.

Instead of returning a false `opentracing::expected` i.e. no value, or returning a unique_ptr to a default-initialized context, it returns a `unique_ptr<opentracing::Context>(nullptr)`. This is surprising to me; why use `opentracing::expected` at all in this case?

https://github.com/jaegertracing/cpp-client/blob/c36adcf7eaf09b548ada784cbb97d40f6b9d6519/src/jaegertracing/Tracer.h#L155

The following test addition illustrates the *current* behaviour if inserted in `src/jaegertracing/TracerTest.cpp`:280 after the declaration of the stringstream, i.e.:

```
        std::stringstream ss;
        opentracing::expected<std::unique_ptr<opentracing::SpanContext>> empty_result = tracer->Extract(ss);
        ASSERT_FALSE(!empty_result);
        ASSERT_EQ(*empty_result, nullptr);
        
```

AFAICS `Extract` should return no-value with info on why, such that a passing test would be

```
        std::stringstream ss;
        opentracing::expected<std::unique_ptr<opentracing::SpanContext>> empty_result = tracer->Extract(ss);
        ASSERT_TRUE(!empty_result);
```

or return a default context e.g.:

```
         if (spanContext == SpanContext()) {
            return std::unique_ptr<opentracing::SpanContext>(new SpanContext());
         }
```

such that a passing test would be

```
        std::stringstream ss;
        opentracing::expected<std::unique_ptr<opentracing::SpanContext>> empty_result = tracer->Extract(ss);
        ASSERT_FALSE(!empty_result);
        ASSERT_NE(*empty_result, nullptr);
        ASSERT_EQ(static_cast<const jaegertracing::SpanContext&>(*(*empty_result)), jaegertracing::SpanContext());
```

Or just doc/comment the current behaviour :)

**Comment by ringerc** [comment]
This mainly means that if you're testing for an extracted context you must

```
        auto ctx = pgtracer->tracer->Extract(ss);
        if (ctx && (*ctx != nullptr))
        {
        }
```

Closing, I don't intend to do anything about this and think it's probably intentional, just an API quirk. Doc'ing for the next person.

**Comment by rnburn** [comment]
It is documented here: https://github.com/opentracing/opentracing-cpp/blob/master/include/opentracing/tracer.h#L131

`expected` is meant to contain either the result or an error ([std::error_code](http://en.cppreference.com/w/cpp/error/error_code)). It uses nullptr since lacking span doesn't really represent an error; i.e. you wouldn't want to do something like
```cpp
auto ctx = pgtracer->tracer->Extract(ss);
if (!ctx) {
  LOG_ERROR(ctx.error().message());
}
```
